[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "portagetool"
version = "1!0.0.1787109853"
description = "Common functions for portage"
authors = [
    { name = "Justin Keogh", email = "github.com@v6y.net" },
]
dependencies = [
    "click",
]
license = "ISC"
requires-python = ">=3.11"

[project.urls]
Homepage = "https://github.com/jakeogh/portagetool"

[project.scripts]
portagetool = "portagetool.portagetool:cli"
emerge_keep = "portagetool.portagetool:emerge_keepwork"

[tool.setuptools]
include-package-data = true
zip-safe = false
packages = ["portagetool"]
script-files = ["io-niceness.sh"]

[tool.setuptools.package-data]
portagetool = [
    "py.typed",
]
